add trix editor, and markdown syntax
Leanpub-simpub/simpub pull request #10
Opened 2020-08-28 08:25 UTC by Parker-ygfert

- 加入 trix & redcarpet 套件
- 新增 content 欄位至 book table
- book new 頁面加入文字編輯器
- 新增 show 頁面

2020-08-28 09:07 UTC, macyjeanma approved these changes
good!mate!

2020-08-28 09:07 UTC, macyjeanma commented on app/controllers/books_controller.rb
> +      redirect_to "/", notice: "YAH~~~"
記得改"YAH~~~"

2020-08-28 14:00 UTC, Chen-Jhen-Ting commented
謝大大貢獻

2020-08-28 14:12 UTC, Chen-Jhen-Ting requested changes
大大們，我把 webpacker 弄好了，請不要繼續在 assets 裡面放東西了

修改在此 PR  #9 ， 等待 review

2020-08-30 02:12 UTC, Tetsu81 approved these changes

2020-08-30 05:22 UTC, jrnalts approved these changes

2020-08-30 05:32 UTC, jrnalts commented
衝突的部分修掉了，但為什麼沒辦法 merge??

2020-08-30 06:37 UTC, Chen-Jhen-Ting approved these changes

2020-08-30 06:37 UTC, merged

2020-08-31 10:29 UTC, macyjeanma reviewed
good